# Generated by Django 2.1.5 on 2019-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('resenia', models.TextField(max_length=500)),
                ('imagen', models.CharField(max_length=100)),
                ('imagenTSS', models.CharField(max_length=100)),
                ('imagenTSS1', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('apodo', models.CharField(max_length=100)),
                ('horarios', models.CharField(max_length=100)),
                ('datosInteres', models.CharField(max_length=100)),
                ('arquitecto', models.CharField(max_length=100)),
                ('importanciaCiudad', models.TextField(max_length=500)),
                ('imagenR', models.CharField(max_length=100)),
                ('patrono', models.CharField(max_length=100)),
                ('principalesCambios', models.TextField(max_length=500)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
