# Generated by Django 2.1.5 on 2019-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='tipo',
            new_name='tipo1',
        ),
        migrations.AlterField(
            model_name='sitio',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='datosInteres',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='imagenR',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='imagenTSS',
            field=models.ImageField(blank=True, null=True, upload_to='imagen360'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='imagenTSS1',
            field=models.ImageField(blank=True, null=True, upload_to='imagen360'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
