# Generated by Django 2.1.5 on 2019-02-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitio_imgqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='imgQR',
            field=models.CharField(max_length=500),
        ),
    ]
